config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "recipes#index"
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
end

app/models/food_preference.rb
class FoodPreference < ApplicationRecord
  has_many :recipes
end

app/models/food_type.rb
class FoodType < ApplicationRecord
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  belongs_to :food_type
  belongs_to :food_preference
  belongs_to :cuisine

  DIFFICULTY = %w(Easy Medium Hard)


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :food_preferences, :food_types, :cuisines

  def food_preferences
    @food_preferences = FoodPreference.all   
  end 
  def food_types
    @food_types = FoodType.all
  end
  def cuisines
    @cuisines = Cuisine.all
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create,
    :update, :destroy]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  helper_method :sidebar_values


  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :cooking_time, :difficulty_level, :food_type_id, :food_preference_id, :cuisine_id, :ingredients, :procedure)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/recipes_helper.rb
module RecipesHelper
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RollRecipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <!-- notice or alert-->    
      <div class="row">
        <div class="col-lg-6">
          <% if notice %>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <p class="mb-0"><%= notice %></p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div> 
          <% end%>
          <% if alert %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <p class="mb-0"><%= alert %></p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <% end %>
        </div>
      </div>
      <!-- end notice or alert -->
    
      <!-- Static navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#"><%= image_tag "excavator.png"%></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      <span class="navbar-toggler-icon"></span>
      <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <%= link_to "Recipes", recipes_path, class: "nav-link active"  %>
            </li>
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "#{current_user.email}", class: "nav-link active"  %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, class: "nav-link active"%>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link active"  %>
            </li>
            <li class="nav-item">
              <%= link_to "SugnUp", new_user_registration_path, class: "nav-link active"%>
            </li>
            <% end %>
          </ul>
        </div>
      </nav>   
      <!-- End static navbar-->

      <!-- Panels-->
      <div class="row">
        <div class="col-lg-3">
          <div class="card">
            <div class="card-body">
              <div class="card-header">
                Food preferences 
              </div>
              <% food_preferences.each do |fp| %>
                <p class="card-text"><%= fp.name %></p>
              <% end %>
            </div>
          </div>
          <div class="card">
            <div class="card-body">
              <div class="card-header">
                Food Types 
              </div>
              <% food_types.each do |ft| %>
                <p class="card-text"><%= ft.name %></p>
              <% end %>
            </div>
          </div>
          <div class="card">
            <div class="card-body">
              <div class="card-header">
                Cuisines 
              </div>
              <% cuisines.each do |c| %>
                <p class="card-text"><%= c.name %></p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-lg-9">
          <%= yield %>
        </div>
      </div>
      <!-- end Panels-->      
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :cooking_time %>
    <%= form.text_field :cooking_time %>
  </div>

  <div class="field">
    <%= form.label :difficulty_level %>
    <%= form.select :difficulty_level, Recipe::DIFFICULTY,{:prompt => 'Please Choose'},:class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :food_type_id %>
    <%= form.select :food_type_id, options_from_collection_for_select(FoodType.all, :id, :name), { :prompt => 'Please Choose' }, :class => "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :food_preference_id %>
    <%= form.select :food_preference_id, options_from_collection_for_select(FoodPreference.all, :id, :name), {:prompt => 'Please Choose'}, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :cuisine_id %>
    <%= form.select :cuisine_id, options_from_collection_for_select(Cuisine.all, :id, :name), {:prompt => 'Please Choose'}, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_area :ingredients %>
  </div>

  <div class="field">
    <%= form.label :procedure %>
    <%= form.text_area :procedure %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Cooking time</th>
      <th scope="col">Difficulty level</th>
      <th scope="col">Food type</th>
      <th scope="col">Food preference</th>
      <th scope="col">Cuisine</th>
      <th scope="col">Ingredients</th>
      <th scope="col">Procedure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.cooking_time %></td>
        <td><%= recipe.difficulty_level %></td>
        <td><%= recipe.food_type.name %></td>
        <td><%= recipe.food_preference.name %></td>
        <td><%= recipe.cuisine.name %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.procedure %></td>
        <td><%= link_to 'Show', recipe, class: "btn btn-primary btn-sm" %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_recipe_path(recipe), class: "btn btn-success btn-sm" %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @recipe.cooking_time %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @recipe.difficulty_level %>
</p>

<p>
  <strong>Food type:</strong>
  <%= @recipe.food_type_id %>
</p>

<p>
  <strong>Food preference:</strong>
  <%= @recipe.food_preference_id %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @recipe.cuisine_id %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Procedure:</strong>
  <%= @recipe.procedure %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>